// <auto-generated />
namespace Animais_Carentes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class melhorando_agendamento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(melhorando_agendamento));
        
        string IMigrationMetadata.Id
        {
            get { return "201810081812040_melhorando_agendamento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
